serviceName: gateway
namespace: martketplace-vkr

replicas: 1

containerPort: 8000

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 32Mi

ingress:
  enabled: true
  host: marketplace.vitalmeuble.online
  port: 8000
